server:
  port: 8001
spring:
  application:
    name: SpringCloudAPI002Provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/phase04
    username: root
    password: root
mybatis:
  type-aliases-package: com.jd.pojo
  config-location: classpath:mybatis.cfg.xml
  mapper-locations:
    - classpath:com/jd/dao/mapper/*.xml